### ISSUE TITLE
Move all ReadFile.c code and references into FileHandler.c

### ISSUE THREAD

**Issue by redstarbird** [redstarbird/arrowpack#30]

**Comment by cryates2** [comment]
Do you want anything done with the associated header files as well?

**Comment by redstarbird** [comment]
> Do you want anything done with the associated header files as well?

Sorry I didn't answer your question because you had already created the commit before I had seen it. Yes, I did want the header files changed as you did. Thank you very much for your contribution

**Comment by redstarbird** [comment]
Completed with commit: https://github.com/redstarbird/arrowpack/commit/08bae6ab42a61c208c79f06368d514994fce5e86
